package sudoku.solver.actions;

import sudoku.solver.solvercontext.*;

/*
An interface for an Action. Actions are generated by Rule and
applied to a SolverBoard to move it closer to a solved state.
*/
public interface Action {
	public void applyAction(SolverBoard inputBoard);
}